[workspace]
members = [
    "src/gqls",
    "src/gqls-base-db",
    "src/gqls-db",
    "src/gqls-ide",
    "src/gqls-ir",
    "src/gqls-fixture",
    "src/gqls-syntax",
    "src/gqls-ty",
    "src/testing",
    "src/vfs",
    "tree-sitter-graphql",
]
